/*
 * generated by Xtext
 */
package org.walter.personas.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalComparator;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;
import org.walter.commons.ui.contentassist.TemplatePreferringCompletionProposalProvider;
import org.walter.personas.ui.editor.syntaxcoloring.PmlHighlightingConfiguration;
import org.walter.personas.ui.editor.syntaxcoloring.PmlSemanticHighlightingCalculator;
import org.walter.personas.ui.editor.templates.PmlTemplateProposalProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PmlUiModule extends org.walter.personas.ui.AbstractPmlUiModule {
	public PmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return PmlHighlightingConfiguration.class;
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator>bindISemanticHighlightingCalculator() {
		return PmlSemanticHighlightingCalculator.class;
	}

	public Class<? extends ICompletionProposalComparator> bindICompletionProposalComparator() {
		return TemplatePreferringCompletionProposalProvider.class;
	}
	
	@Override
	public Class<? extends ITemplateProposalProvider> bindITemplateProposalProvider() {
		return PmlTemplateProposalProvider.class;
	}
}
