/*
 * generated by Xtext
 */
package org.walter.personas;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PmlStandaloneSetup extends PmlStandaloneSetupGenerated{

	public static void doSetup() {
		new PmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

